<?php
/**
 * Cybage Multifilter Layered Navigation Plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_ecom@cybage.com.  We will send you a copy of the source file.
 *
 * @category   Multifilter Layered Navigation Plugin
 * @package    Cybage_Multifilter
 * @copyright  Copyright (c) 2015 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_ecom@cybage.com>
 */
?>
<?php
/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currentPage = $objectManager->get('\Magento\Framework\Session\SessionManager')->getCurrentPage();
if ($block->getCollection()->getSize()):
    ?>

    <?php if ($block->getUseContainer()): ?>
        <div class="pager">
        <?php endif ?>
        <?php if ($block->getLastPageNum() > 1): ?>
            <div class="pages">
                <strong class="label pages-label" id="paging-label"><?php /* @escapeNotVerified */ echo __('Page') ?></strong>
                <ul class="items pages-items" aria-labelledby="paging-label">
                    <?php if($currentPage != '' && $currentPage!='1'): ?>
                        <li class="item pages-item-previous">
                            <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : ''; ?>
                            <a  onclick="getNextCollection('<?php echo $currentPage-1;?>')" class="<?php /* @escapeNotVerified */ echo $text ? 'link ' : 'action ' ?> previous" href="javascript:void(0)<?php /* @escapeNotVerified */ //echo $block->getPreviousPageUrl() ?>" title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Previous') ?>">
                                <span class="label"><?php /* @escapeNotVerified */ echo __('Page') ?></span>
                                <span><?php /* @escapeNotVerified */ echo $text ? $text : __('Previous') ?></span>
                            </a>
                        </li>
                    <?php endif; ?>

                    <?php if ($block->canShowFirst()): ?>
                        <li class="item">
                            <a class="page first" href="javascript:void(0)<?php /* @escapeNotVerified */ //echo $block->getFirstPageUrl()  ?>">
                                <span class="label"><?php /* @escapeNotVerified */ echo __('Page') ?></span>
                                <span>1</span>
                            </a>
                        </li>
                    <?php endif; ?>

                    <?php if ($block->canShowPreviousJump()): ?>
                        <li class="item">
                            <a class="page previous jump" title="" href="javascript:void(0)<?php /* @escapeNotVerified */ //echo $block->getPreviousJumpUrl() ?>">
                                <span>...</span>
                            </a>
                        </li>
        <?php endif; ?>

                    <?php foreach ($block->getFramePages() as $_page): ?>
                        <?php 
                        $checkPage = $currentPage!= ''?$currentPage:'1';
                        if ($checkPage == $_page): ?>
                            
                        <li class="item current">
                                <strong class="page">
                                    <span class="label"><?php /* @escapeNotVerified */ echo __('You\'re currently reading page') ?></span>
                                    <span><?php /* @escapeNotVerified */ echo $_page ?></span>
                                </strong>
                            </li>
            <?php else: ?>
                            <li class="item">
                                <a onclick="getNextCollection('<?php /* @escapeNotVerified */ echo $_page ?>')" href="javascript:void(0)<?php /* @escapeNotVerified */ //echo $block->getPageUrl($_page)  ?>" class="page">
                                    <span class="label"><?php /* @escapeNotVerified */ echo __('Page') ?></span>
                                    <span><?php /* @escapeNotVerified */ echo $_page ?></span>
                                </a>
                            </li>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if ($block->canShowNextJump()): ?>
                        <li class="item">
                            <a class="page next jump" title="" href="javascript:void(0)<?php /* @escapeNotVerified */ //echo $block->getNextJumpUrl() ?>">
                                <span>...</span>
                            </a>
                        </li>
        <?php endif; ?>

        <?php if ($block->canShowLast()): ?>
                        <li class="item">
                            <a class="page last" href="javascript:void(0)<?php /* @escapeNotVerified */ //echo $block->getLastPageUrl()  ?>">
                                <span class="label"><?php /* @escapeNotVerified */ echo __('Page') ?></span>
                                <span><?php /* @escapeNotVerified */ echo $block->getLastPageNum() ?></span>
                            </a>
                        </li>
        <?php endif; ?>

        <?php 
        $nextPage = $currentPage != ''?$currentPage:'1';
        if (!$block->isLastPage()): ?>
                        <li class="item pages-item-next">
                        <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : ''; ?>
                            <a onclick="getNextCollection('<?php echo $nextPage+1;?>')"class="<?php /* @escapeNotVerified */ echo $text ? 'link ' : 'action ' ?> next" href="javascript:void(0)<?php /* @escapeNotVerified */ //echo $block->getNextPageUrl() ?>" title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Next') ?>">
                                <span class="label"><?php /* @escapeNotVerified */ echo __('Page') ?></span>
                                <span><?php /* @escapeNotVerified */ echo $text ? $text : __('Next') ?></span>
                            </a>
                        </li>
        <?php endif; ?>
                </ul>
            </div>
    <?php endif; ?>



        <?php if ($block->getUseContainer()): ?>
        </div>
    <?php endif ?>

    <?php endif ?>
<script>
    function getNextCollection(value){
        var selectedFilter = [];
        jQuery('.multifilter').each(function(index,element){
            if(jQuery(this).is(':checked')){
                selectedFilter.push(jQuery(this).val());
            }
        });
        jQuery('#ajaxloader').show();
        jQuery('#overlaydiv').show();
        jQuery.ajax({
            url: "/multifilter/category/ajax",
            type: "POST",
            data: {"currentLimit":jQuery('#limiter').val(),"currentSortOpt":jQuery('#sorter').val(),"checkedFilter":selectedFilter,"currentPage":value},
            dataType: "html",
            success: function(data) {
                jQuery('#ajaxloader').hide();
                jQuery('#overlaydiv').hide();
                jQuery('#result_data').html(data);
                jQuery('#ajaxcollection').show();
                jQuery('#corecollection').hide();
            }
        });
        
    }
</script>