<?php
/**
 * Cybage Multifilter Layered Navigation Plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_ecom@cybage.com.  We will send you a copy of the source file.
 *
 * @category   Multifilter Layered Navigation Plugin
 * @package    Cybage_Multifilter
 * @copyright  Copyright (c) 2015 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_ecom@cybage.com>
 */
?>
<?php

use Magento\Framework\App\Action\Action;

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$type = $this->multifilterSession->getType();
$categories = $this->coreRegistry->registry('catagories');
$currentLimit = $this->coreRegistry->registry('activeLimit');
$currentSortOpt = $this->coreRegistry->registry('activeSortOpt');
$attributes = $this->coreRegistry->registry('attributes');
$_productCollection = '';

if ($type=='coreblock') {
    $_productCollection = $block->getLoadedProductCollection();
} else {
    $implodedArr = $objectManager->get('\Cybage\Multifilter\Controller\Category\View')->getProducts($categories, $attributes);
    $_productCollection = $objectManager->get('\Cybage\Multifilter\Controller\Category\View')->getParentCollection($implodedArr, $currentLimit, $currentSortOpt);
    
}
?>
<div style="background: #000; width: 100%; height: 100%; opacity: 0.5; position: absolute; display: none; top: 0; z-index: 99" id="overlaydiv"></div>
<div id="ajaxloader" style="display:none;position: absolute;left:60%; top: 10%; z-index: 999;">
    <img src="<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>"/>
</div>    
<div id="result_data">
<?php
if (empty($categories) && empty($attributes)) {
    ?>
        <div id="corecollection">
        <?php
        $_helper = $this->helper('Magento\Catalog\Helper\Output');
        if (!$_productCollection->count()):
            ?>
                <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
            <?php else: ?>
                <?php echo $block->getToolbarHtml() ?>
                <?php echo $block->getAdditionalHtml() ?>
                <?php
                if ($block->getMode() == 'grid') {
                    $viewMode = 'grid';
                    $image = 'category_page_grid';
                    $showDescription = false;
                    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
                } else {
                    $viewMode = 'list';
                    $image = 'category_page_list';
                    $showDescription = true;
                    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
                }
                /**
                 * Position for actions regarding image size changing in vde if needed
                 */
                $pos = $block->getPositioned();
                ?>
                <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
                <?php $iterator = 1; ?>
                    <ol class="products list items product-items">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product): ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <div class="product-item-info" data-container="product-grid">
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                                <?php // Product Image ?>
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                                </a>
                                <div class="product details product-item-details">
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
                                               <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>

                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                            <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
            <?php if ($_product->isSaleable()): ?>
                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                <?php echo $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart primary">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    </form>
            <?php else: ?>
                <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                            <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#"
                                                       class="action towishlist"
                                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist"
                                                       role="button">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                    </a>
            <?php endif; ?>
            <?php
            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
            ?>
                                                <a href="#"
                                                   class="action tocompare"
                                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                                   role="button">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                </a>
                                            </div>
                                        </div>
            <?php if ($showDescription): ?>
                                            <div class="product description product-item-description">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                                   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                            </div>
            <?php endif; ?>
                                    </div>
                                </div>
                            </div>
            <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
        <?php endforeach; ?>
                    </ol>
                </div>
                        <?php echo $block->getToolbarHtml() ?>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
                    <script type="text/x-magento-init">
                        {
                        "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCart": {}
                        }
                        }
                    </script>
        <?php endif; ?>
    <?php endif; ?>


        </div>
<?php }
?>
        <div id="ajaxcollection" style="display:none">
    

    <?php
        if (empty($_productCollection)):
        ?>
            <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
        <?php else: ?>
            <?php echo $block->getToolbarHtml() ?>
            <?php echo $block->getAdditionalHtml() ?>
            <?php
             $viewMode = $this->multifilterSession->getViewMode();
             $mode = $viewMode == ''?'grid':$viewMode;
            if ($mode == 'grid') {
                $viewMode = 'grid';
                $image = 'category_page_grid';
                $showDescription = false;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            } else {
                $viewMode = 'list';
                $image = 'category_page_list';
                $showDescription = true;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
            }
            /**
             * Position for actions regarding image size changing in vde if needed
             */
            $pos = $block->getPositioned();
            ?>
            <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
            <?php $iterator = 1; ?>
                <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php 
                $productCount = count($_productCollection->getData());
                $this->multifilterSession->settotalCount($productCount);
                foreach ($_productCollection as $_product):
                    ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                        <div class="product-item-info" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                            <?php // Product Image ?>
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                            </a>
                            <div class="product details product-item-details">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
        <?php /* @escapeNotVerified */ echo $objectManager->get('\Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
                                           <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                <?php if($block->isAjax()) {
                                echo $block->getProductDetailsHtml($_product);
                                } ?> 

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
        <?php if ($_product->isSaleable()): ?>
            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
            <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
        <?php else: ?>
            <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                            <?php if ($objectManager->get('\Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#"
                                                   class="action towishlist"
                                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
        <?php endif; ?>
        <?php
        $compareHelper = $objectManager->get('\Magento\Catalog\Helper\Product\Compare');
        ?>
                                            <a href="#"
                                               class="action tocompare"
                                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                               role="button">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                            </a>
                                        </div>
                                    </div>
        <?php if ($showDescription): ?>
                                        <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */ echo $objectManager->get('\Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                               class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                        </div>
        <?php endif; ?>
                                </div>
                            </div>
                        </div>
        <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
    <?php endforeach; ?>
                </ol>
            </div>
                    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
                <script type="text/x-magento-init">
                    {
                    "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {}
                    }
                    }
                </script>
    <?php endif; ?>
<?php endif; ?>

           </div>
</div>
